### PR TITLE
fix(cloudflare): local runtime cache `astro dev`

### PR DESCRIPTION
**Pull request by alexanderniebuhr**
## Changes

- What does this change?
- Be short and concise. Bullet points can help!
- Before/after screenshots can help as well.
- Don't forget a changeset! `pnpm exec changeset`

### CODE REVIEW

**Comment by alexanderniebuhr** [comment]
Current dependencies on/for this PR:
* main
  * **PR #48** <a href="https://app.graphite.dev/github/pr/withastro/adapters/48" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/withastro/adapters/48?utm_source=stack-comment).

**Comment by alexanderniebuhr** [comment]
!preview mf-local-cache-patch

**Comment by alexanderniebuhr** [comment]
!preview mf-local-cache-patch

**Review by matthewp — APPROVED** [review]

**Comment by alexanderniebuhr** [comment]
Not going to ship this, but can point people to it, if needed.

**Comment by alexanderniebuhr** [comment]
```
diff --git a/dist/src/index.js b/dist/src/index.js
index 73c59ba08f0b2a251fd805e183fc81394875d79e..40d1f86bdad9ca2a63656b682ad60b349efb340c 100644
--- a/dist/src/index.js
+++ b/dist/src/index.js
@@ -2885,7 +2885,7 @@ var structuredSerializableRevivers = {
 function createHTTPReducers(impl) {
   return {
     Headers(val) {
-      if (val instanceof impl.Headers)
+      if (val instanceof impl.Headers || val.constructor.name == "Headers")
         return Object.fromEntries(val);
     },
     Request(val) {
@@ -2894,7 +2894,7 @@ function createHTTPReducers(impl) {
       }
     },
     Response(val) {
-      if (val instanceof impl.Response) {
+      if (val instanceof impl.Response || val.constructor.name == "Response") {
         return [val.status, val.statusText, val.headers, val.cf, val.body];
       }
     }
```

**Pull request closed without merging**
