### PR TITLE
Reduce amount of rules in routes json file

### PR DESCRIPTION
**Pull request by veitbjarsch**
## Changes
Cloudflare has a limit of 100 includes/exclude rules. In many applications this amount is reached quite fast.
This PR add the functionality to compare include and exclude rules and reduce the amount of rules wherever possible.
Therefore it:
- adds a wildcard if a folder only belogs to include or exclude rules
- skips all subfolders where a wildcard is already present (leave them untouched)

## Testing

Tested in out own project using cloudflare as well wrote a unit test here.

### CODE REVIEW

**Comment by alexanderniebuhr** [comment]
> adds a wildcard if a folder only belogs to include or exclude rules

I have to check this internally, but I think we can't tell this upfront, either in all cases or in specific cases.

> skips all subfolders where a wildcard is already present (leave them untouched)

That's a good addition, we need to see how it handles the routes if you have all static in one folder and then one dynamic route in a nested subfolder. I'll take a look at your testcase.

**Comment by veitbjarsch** [comment]
@alexanderniebuhr Thanks for your fast response.

>> skips all subfolders where a wildcard is already present (leave them untouched)
>
> That's a good addition, we need to see how it handles the routes if you have all static in one folder and then one dynamic route in a nested subfolder. I'll take a look at your testcase.

The code compares both includes and excludes in 2 ways. This means if the same folder (partial path) is present in both PathTrie objects, it will leave them untouched. Only if a folder is not present in the other PathTrie object we can savely assume that all children belongs to the current PathTrie. Only in this case we add the wildcard flag for this folder.

This way we can reduce the amount of rules in our project by more than 50% automatically, without the need to create and handle the routes.jsnon manually.

**Comment by alexanderniebuhr** [comment]
Sounds good, I did a quick test and it seems to be working with all the cases. I'll give it a proper review later :)

**Comment by veitbjarsch** [comment]
Thanks

**Comment by alexanderniebuhr** [comment]
@veitbjarsch can you add an changeset with `pnpm exec changeset`

**Comment by veitbjarsch** [comment]
@alexanderniebuhr added the changeset.

**Review by alexanderniebuhr — APPROVED** [review]

**Comment by veitbjarsch** [comment]
@alexanderniebuhr Hey, is it planned to merge this PR into the main branch?

**Pull request merged**
