### PR TITLE
chore: add script to generate discord release notification

### PR DESCRIPTION
**Pull request by alexanderniebuhr**
## Changes

- What does this change?
- Be short and concise. Bullet points can help!
- Before/after screenshots can help as well.
- Don't forget a changeset! `pnpm exec changeset`

### CODE REVIEW

**Comment by alexanderniebuhr** [comment]
Current dependencies on/for this PR:
* main
  * **PR #23** <a href="https://app.graphite.dev/github/pr/withastro/adapters/23" target="_blank">Graphite</a> 
    * **PR #25** <a href="https://app.graphite.dev/github/pr/withastro/adapters/25" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/withastro/adapters/25?utm_source=stack-comment).

**Comment by alexanderniebuhr** [comment]
Oh no, it is just the next PR in the stack. I can move it up to the parent.

**Comment by lilnasy** [comment]
I don't understand this workflow. What's the stack?

**Comment by alexanderniebuhr** [comment]
> What's the stack?

- https://stacking.dev/
- https://graphite.dev/

**Review by matthewp — APPROVED** [review]

**Comment by lilnasy** [comment]
Wouldn't this prevent the current PR from merging until that unrelated PR is merged, and this branch has rebased or dropped the miniflare commit?

**Pull request merged**
