### PR TITLE
chore: add changeset for netlify

### PR DESCRIPTION
**Pull request by alexanderniebuhr**
## Changes

- adds the already approved changeset for netlify but with `4.0.0` instead of `4.2.0`

### CODE REVIEW

**Comment by alexanderniebuhr** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #138** <a href="https://app.graphite.dev/github/pr/withastro/adapters/138?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/withastro/adapters/138?utm_source=stack-comment).

**Comment by Skn0tt** [comment]
I don't get this. Didn't we discuss not to cut a major release for the Netlify adapter?

**Comment by Skn0tt** [comment]
Re-read your comment now, and see you referring to two major releases. Well, let's do it I guess.

**Comment by Skn0tt** [comment]
Fair, thanks for explaining! Didn't realise that

**Comment by Skn0tt** [comment]
If that's the case, could we maybe do the `> 4.2` peer dependency bump as well? Sorry for the hickhack, I misunderstood. Really want to prevent too many major releases, though :D

**Comment by alexanderniebuhr** [comment]
Sure :)

**Pull request merged**
