### PR TITLE
feat(netlify): v2 functions

### PR DESCRIPTION
**Pull request by lilnasy**
## Changes
- In October, Netlify introduced a new API for functions, called [Functions 2.0](https://www.netlify.com/blog/introducing-netlify-functions-2-0/). The more familiar API is now referred to as [lambda-compatible](https://www.netlify.com/blog/introducing-netlify-functions-2-0/#lambda-compatibility-mode).
- The new API is standards based so would be much easier to maintain (The server entrypoint is 4 lines of code!).
- It streams responses by default, allowing users to improve page load performance.

## Testing
_Pending_

## Docs
_Pending_

### CODE REVIEW

**Comment by alexanderniebuhr** [comment]
@lilnasy status update?

**Comment by lilnasy** [comment]
!preview v2

**Comment by lilnasy** [comment]
!preview v2

**Comment by lilnasy** [comment]
!preview v2

**Comment by lilnasy** [comment]
!preview v2

**Pull request closed without merging**
